### ISSUE TITLE
我按照你的说明引入了， 但是找不到文件

### ISSUE THREAD

**Issue by anming-john** [lucaszhu2zgf/mp-progress#23]
![image](https://user-images.githubusercontent.com/15686326/101881864-0222bf00-3bd0-11eb-868e-89b0403682b4.png)

![image](https://user-images.githubusercontent.com/15686326/101881884-0a7afa00-3bd0-11eb-932e-2094e39c8920.png)

**Comment by lucaszhu2zgf** [comment]
你这是原生的小程序吗？

**Comment by lucaszhu2zgf** [comment]
你写的是原生小程序？@ @anming-john

**Comment by anming-john** [comment]
是的， 原生的

**Comment by lucaszhu2zgf** [comment]
> 是的， 原生的
参考一下这个哈，原生的小程序安装会有点差别
https://developers.weixin.qq.com/community/develop/article/doc/0008aecec4c9601e750be048d51c13

**Comment by lucaszhu2zgf** [comment]
> 是的， 原生的


参考一下这个哈，原生的小程序安装会有点差别
https://developers.weixin.qq.com/community/develop/article/doc/0008aecec4c9601e750be048d51c13

**Comment by lucaszhu2zgf** [comment]
@anming-john 参考一下这个哈，原生的小程序安装会有点差别 
https://developers.weixin.qq.com/community/develop/article/doc/0008aecec4c9601e750be048d51c13
