### ISSUE TITLE
canvasSize 除开400以外的宽高计算有误

### ISSUE THREAD

**Issue by coolguy001tv** [lucaszhu2zgf/mp-progress#31]
![image](https://user-images.githubusercontent.com/936825/118658339-de1e7600-b81e-11eb-94c2-66fe3f4e454f.png)
如图，设置的300宽高，实际渲染的canvas的确是150，但是里边的圆圈其实没有到150

**Comment by lucaszhu2zgf** [comment]
https://github.com/lucaszhu2zgf/mp-progress/blob/905a1c07463688d017a3544c0001acab7860c9c1/src/index.js#L275-L281
换算比例不对哈，源码里面有换算的方式

**Comment by lucaszhu2zgf** [comment]
mp-progress中的canvas是使用的默认值400去初始化的，然后虽然传入了新的参数，比如width传入300，但开发工具中还是用400去做渲染，因此优化了width和height的初始化，并在wxml中加上了wx:if={{customOptions.canvasSize.width}} 来解决问题。
